### ISSUE TITLE
Bug in Vocal when using on User Model with passwords User::create returns unhashed password

### ISSUE THREAD

**Issue by gxela** [sjdaws/vocal#13]
There is a bug in vocal that when creating User will return the $user with password unhashed

    $user_with_unhashed_password = User::create($input_with_hashed_password);

**Comment by sjdaws** [comment]
`create` is not a Vocal method, and because Laravel uses `new static` instead of `new self` to create a new model you will need to create the class then save.

```php
    $data = array('username' => 'test', 'password' => 'password'); // Password must be unhashed if you're expecting it to hash automatically (using $hashAttributes) otherwise it will hash twice

    $user = new User;
    $user->fill($input_with_hashed_password); // Or Input::merge($data); or Input::replace($data);
    $user->save();
```

However, this is a simple fix so I will add a create method shortly.

**Comment by sjdaws** [comment]
[Create method](https://github.com/sjdaws/vocal#create) has been added. You can use it the same as Laravel `create` or you can just let it take input. It will create the model recursively in the same way `saveRecursive` does so you can pass all user information in one form if you want.

```php
    $user = User::create(); // Will read information from Input::all()
    // or
    $user = User::create(array('username' => 'test', 'password' => 'password'));
```

**Comment by gxela** [comment]
Can you tag this as version 1.0.2, so that we can use it with composer and not have to use dev-master

**Comment by sjdaws** [comment]
This was tagged in [1.0.1](https://github.com/sjdaws/vocal/releases/tag/1.0.1) there have been no further commits to master since I released that.

**Comment by gxela** [comment]
ok great, thanks
