### ISSUE TITLE
Save recursive and delete

### ISSUE THREAD

**Issue by josericardomcastro** [sjdaws/vocal#14]
Hello,

First, this is an amazing component. But i have a problem when i want to update the relationships.

User (id, name)
UserPhone (id, user_id, number_phone)

If the user (id=1) has five phone numbers recorded in the database, when pass a json with user object and an array with two userPhone object, i want to delete the others 3 number in the database.

**Comment by sjdaws** [comment]
Hi there,

Sorry about the delay in replying, are you requesting an additional method `saveAndDelete()` or do you think this should be handled by `save()`?

**Comment by sjdaws** [comment]
If you could let me know how you see this being implemented please let me know and reopen this ticket.
